# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  legalisspace-mongodb:
    image: mongo:4.4.8
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 27017:27017
    volumes:
      - ~/Dev/legalis-space/data/mongodb/:/data/db/
  legalisspace-mongo-express:
    depends_on:
      - "legalisspace-mongodb"
    command: >
      /bin/bash -c "sleep 15; tini -- /docker-entrypoint.sh;"
    environment:
      ME_CONFIG_MONGODB_SERVER: legalisspace-mongodb
      ME_CONFIG_MONGODB_AUTH_DATABASE: LegalisSpace
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "false"
      WAIT_HOSTS: legalisspace-mongodb:27017
    image: mongo-express
    ports:
      - 8081:8081
